version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1024m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=8"
      TERM: dumb
    steps:
      - checkout
      - run: echo $CIRCLE_JOB
      - run:
          name: Single command -  echo
          command: echo $CIRCLE_USERNAME
      - run:
          name: Multi-line commands - echo & echo
          command: |
            echo $CIRCLE_REPOSITORY_URL
            echo $CIRCLE_BRANCH


